### ISSUE TITLE
sentiment_analysis.py not working

### ISSUE THREAD

**Issue by brunodpoliveira** [brunodpoliveira/twittter-sentiment-analysis#1]
Traceback (most recent call last):
  File "/home/bruno/MEGA/ml/twittter-sentiment-analysis-main/naive-bayes/sentiment_analysis.py", line 102, in <module>
    NBayesClassifier = nltk.NaiveBayesClassifier.train(training_features)
  File "/home/bruno/MEGA/ml/twittter-sentiment-analysis-main/venv/lib/python3.8/site-packages/nltk/classify/naivebayes.py", line 207, in train
    for featureset, label in labeled_featuresets:
  File "/home/bruno/MEGA/ml/twittter-sentiment-analysis-main/venv/lib/python3.8/site-packages/nltk/collections.py", line 414, in iterate_from
    yield self._func(self._lists[0][index])
TypeError: 'NoneType' object is not subscriptable

Process finished with exit code 1

**Comment by brunodpoliveira** [comment]
Started new approach - see sentiment_analysis_simple
